# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set([('user_id', 'event_id')]),
        ),
    ]
